DROP TABLE REVIEW_COMMENT;
DROP TABLE CART;
DROP TABLE REVIEW;
DROP TABLE ORDER_DETAIL;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER_SERVICE;
DROP TABLE MEMBER;
DROP TABLE PRODUCT;
DROP TABLE DELIVERY;
DROP TABLE GRADES;
DROP TABLE AD;
DROP TABLE MANAGER;

DROP SEQUENCE ADNO_SEQ;
DROP SEQUENCE ONO_SEQ;
DROP SEQUENCE DNO_SEQ;
DROP SEQUENCE CNO_SEQ;
DROP SEQUENCE CTNO_SEQ;
DROP SEQUENCE RNO_SEQ;
DROP SEQUENCE ODNO_SEQ;
DROP SEQUENCE RCNO_SEQ;
DROP SEQUENCE RGNO_SEQ;

CREATE SEQUENCE ADNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE ONO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE ODNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE DNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE CNO_SEQ --CUSTOMER_SERVICE
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE CTNO_SEQ --CART
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE RNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE RGNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;
CREATE SEQUENCE RCNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;
CREATE TABLE GRADES(
    GNO NUMBER(1) PRIMARY KEY,
    GNAME VARCHAR2(30) NOT NULL,
    LOWGRADE NUMBER(9) NOT NULL,
    HIGHGRADE NUMBER(9) NOT NULL);

CREATE TABLE MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MPHONE VARCHAR2(30) NOT NULL,
    MADDRESS_BASIC VARCHAR2(100),
    MADDRESS_DETAIL VARCHAR2(100),
    MBIRTH DATE,
    MEMAIL VARCHAR2(100),
    MGENDER VARCHAR2(30) NOT NULL,
    MPOINT NUMBER(9) DEFAULT 0,
    MCUMULATIVE_BUY NUMBER(9) DEFAULT 0,
    MJOINDATE DATE DEFAULT SYSDATE,
    MSTATUS NUMBER(1) DEFAULT 0 );

CREATE TABLE AD(
    MID VARCHAR2(30) PRIMARY KEY,
    AD_EMAIL NUMBER(1) DEFAULT 0,  -- 1이 수락 0이 거절
    AD_PHONE NUMBER(1) DEFAULT 0,
    AD_CALL NUMBER(1) DEFAULT 0 );
    
CREATE TABLE CUSTOMER_SERVICE(
    CNO NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MEMBER(MID),
    CSUBJECT VARCHAR2(100) NOT NULL,
    CCONTENT VARCHAR2(4000),
    CSECRET NUMBER(1) DEFAULT 0,  --1이 공개
    CIMAGE VARCHAR2(30),
    CHIT NUMBER(6) DEFAULT 0,
    CGROUP NUMBER(6) NOT NULL,
    CGROUP_OUTNUM NUMBER(6) DEFAULT 0,
    CINDENT NUMBER(6) DEFAULT 0,
    CRDATE DATE DEFAULT SYSDATE,
    ONO NUMBER(6)
);
CREATE TABLE DELIVERY(
    DNO NUMBER(6) PRIMARY KEY,
    DPRICE NUMBER(6) NOT NULL,
    DCOMPANY VARCHAR2(30) NOT NULL,
    ODATE DATE DEFAULT SYSDATE,
    PARRIVE_DATE DATE);
    
CREATE TABLE ORDERS(
    ONO NUMBER(6) PRIMARY KEY,
    ODATE DATE DEFAULT SYSDATE,
    PARRIVE_DATE DATE,
    PURCHASE_AMOUNT NUMBER(9),
    DNO NUMBER(6) REFERENCES DELIVERY(DNO),
    MID VARCHAR2(30) REFERENCES MEMBER(MID) );

CREATE TABLE MANAGER(
    MGID VARCHAR2(30) PRIMARY KEY,
    MGPW VARCHAR2(30) NOT NULL,
    MGNAME VARCHAR2(30) NOT NULL,
    MGPARTNAME VARCHAR2(30) NOT NULL
);

CREATE TABLE PRODUCT(
    PCODE VARCHAR2(30) PRIMARY KEY,
    MGID VARCHAR2(30) REFERENCES MANAGER(MGID),
    PNAME VARCHAR2(30) NOT NULL,
    PPRICE NUMBER(9) NOT NULL,
    PIMAGE VARCHAR2(30),
    PSTOCK NUMBER(6) NOT NULL,
    PDESCRIPTION VARCHAR2(1000),
    PDISCOUNT NUMBER(3) DEFAULT 0,
    PREGIST DATE DEFAULT SYSDATE,
    PCUMULATIVE_SALES NUMBER(6) DEFAULT 0,
    PREVIEW_COUNT NUMBER(6) DEFAULT 0 );

CREATE TABLE ORDER_DETAIL(
    ODNO NUMBER(6) PRIMARY KEY,
    ONO NUMBER(6) REFERENCES ORDERS(ONO),
    PCODE VARCHAR2(30) REFERENCES PRODUCT(PCODE),
    PCNT NUMBER(6) DEFAULT 1 NOT NULL,
    PPRICE NUMBER(9) NOT NULL );
    
CREATE TABLE REVIEW(
    RNO NUMBER(6) PRIMARY KEY,
    PCODE VARCHAR2(30) REFERENCES PRODUCT(PCODE),
    MID VARCHAR2(30) REFERENCES MEMBER(MID),
    RIMAGE1 VARCHAR2(30),
    RIMAGE2 VARCHAR2(30),
    RIMAGE3 VARCHAR2(30),
    RGOOD NUMBER(6) DEFAULT 0,
    RSTAR NUMBER(6) DEFAULT 10,
    RCONTENT VARCHAR2(4000),
    RDATE DATE DEFAULT SYSDATE);

CREATE TABLE REVIEW_RGOOD(
    RGNO NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(30) NOT NULL,
    RNO NUMBER(6) REFERENCES REVIEW(RNO) );

CREATE TABLE CART(
    CTNO NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MEMBER(MID),
    PCODE VARCHAR2(30) REFERENCES PRODUCT(PCODE),
    PCNT NUMBER(6) NOT NULL,
    PPRICE NUMBER(9) NOT NULL
);

CREATE TABLE REVIEW_COMMENT(
    RCNO NUMBER(6) PRIMARY KEY,
    RNO NUMBER(6) REFERENCES REVIEW(RNO),
    MGID VARCHAR2(30) REFERENCES MANAGER(MGID),
    RCCONTENT VARCHAR2(4000)
);

INSERT INTO GRADES (GNO, GNAME, LOWGRADE, HIGHGRADE)
VALUES (1,'NORMAL',0,1000000);
INSERT INTO GRADES (GNO, GNAME, LOWGRADE, HIGHGRADE)
VALUES (2,'GOLD',1000001,10000000);
INSERT INTO GRADES (GNO, GNAME, LOWGRADE, HIGHGRADE)
VALUES (3,'VIP',10000001,10000000);
INSERT INTO GRADES (GNO, GNAME, LOWGRADE, HIGHGRADE)
VALUES (4,'VVIP',10000001,999999999);


COMMIT;

