
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE GRADE CASCADE CONSTRAINTS;
DROP TABLE AD;

CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 99999
    NOCYCLE
    NOCACHE;

CREATE TABLE GRADE(
    GNO NUMBER(1) PRIMARY KEY,
    GNAME VARCHAR2(30) NOT NULL,
    LOWGRADE NUMBER(9),
    HIGHGRADE NUMBER(9) );

CREATE TABLE MEMBER(
    MNO NUMBER(5) PRIMARY KEY,
    MID VARCHAR2(30) UNIQUE,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MPHONE VARCHAR2(30) NOT NULL,
    MADDRESS VARCHAR2(100),
    MBIRTH DATE,
    MEMAIL VARCHAR2(100),
    MJOINDATE DATE DEFAULT SYSDATE,
    GNO NUMBER(1) REFERENCES GRADE(GNO) );

CREATE TABLE AD(
    MNO NUMBER(5) PRIMARY KEY REFERENCES MEMBER(MNO),
    AD_EMAIL NUMBER(1),
    AD_PHONE NUMBER(1) );
    
SELECT * FROM MEMBER;
SELECT * FROM GRADE;
SELECT * FROM AD;
