DROP TABLE REVIEW_FILE;
DROP TABLE REVIEW;
DROP TABLE ORDER_DETAIL;
DROP TABLE ORDERS;
DROP TABLE CUSTOMER_SERVICE;
DROP TABLE MEMBER;
DROP TABLE PRODUCT;
DROP TABLE DELIVERY;
DROP TABLE GRADES;
DROP TABLE AD;

DROP SEQUENCE ADNO_SEQ;
DROP SEQUENCE ONO_SEQ;
DROP SEQUENCE DNO_SEQ;
DROP SEQUENCE CNO_SEQ;
DROP SEQUENCE RNO_SEQ;
DROP SEQUENCE RFNO_SEQ;
DROP SEQUENCE ODNO_SEQ;


CREATE SEQUENCE ADNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE ONO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE ODNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE DNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE CNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE RNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE RFNO_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;


CREATE TABLE GRADES(
    GNO NUMBER(1) PRIMARY KEY,
    GNAME VARCHAR2(30) NOT NULL,
    LOWGRADE NUMBER(9) NOT NULL,
    HIGHGRADE NUMBER(9) NOT NULL);

CREATE TABLE MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MPHONE VARCHAR2(30) NOT NULL,
    MADDRESS VARCHAR2(100),
    MBIRTH DATE,
    MEMAIL VARCHAR2(100),
    MGENDER VARCHAR2(30),
    MPOINT NUMBER(9) DEFAULT 0,
    MCUMULATIVE_BUY NUMBER(9) DEFAULT 0,
    MJOINDATE DATE DEFAULT SYSDATE,
    GNO NUMBER(1) REFERENCES GRADE(GNO) );

CREATE TABLE AD(
    MID VARCHAR2(30) PRIMARY KEY,
    AD_EMAIL NUMBER(1) DEFAULT 0,  -- 1이 수락 0이 거절
    AD_PHONE NUMBER(1) DEFAULT 0,
    AD_CALL NUMBER(1) DEFAULT 0 );
    
CREATE TABLE CUSTOMER_SERVICE(
    CNO NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MEMBER(MID),
    CCONTENT VARCHAR2(4000),
    CSECRET NUMBER(1) DEFAULT 0,  --1이 공개
    CHIT NUMBER(6) DEFAULT 0,
    CGROUP NUMBER(6) DEFAULT 0,
    CGROUP_OUTNUM NUMBER(6) DEFAULT 0,
    CINDENT NUMBER(6) DEFAULT 0,
    ONO VARCHAR2(30)
);

CREATE TABLE DELIVERY(
    DNO VARCHAR2(30) PRIMARY KEY,
    DPRICE NUMBER(6) NOT NULL,
    DCOMPANY VARCHAR2(30) NOT NULL,
    ODATE DATE DEFAULT SYSDATE,
    PARRIVE_DATE DATE);
    
CREATE TABLE ORDERS(
    ONO VARCHAR2(30) PRIMARY KEY,
    ODATE DATE DEFAULT SYSDATE,
    PARRIVE_DATE DATE,
    DNO VARCHAR2(30) REFERENCES DELIVERY(DNO),
    MID VARCHAR2(30) REFERENCES MEMBER(MID) );
    
CREATE TABLE PRODUCT(
    PCODE VARCHAR2(30) PRIMARY KEY,
    PNAME VARCHAR2(30) NOT NULL,
    PPRICE NUMBER(9) NOT NULL,
    PSTOCK NUMBER(6) NOT NULL,
    PDISCOUNT NUMBER(3) DEFAULT 0,
    PREGIST DATE DEFAULT SYSDATE,
    PCUMULATIVE_SALES NUMBER(6) DEFAULT 0,
    PREVIEW_COUNT NUMBER(6) DEFAULT 0 );

CREATE TABLE ORDER_DETAIL(
    ODNO VARCHAR2(30) PRIMARY KEY,
    ONO VARCHAR2(30) REFERENCES ORDERS(ONO),
    PCODE VARCHAR2(30) REFERENCES PRODUCT(PCODE),
    PCNT NUMBER(6) DEFAULT 1 NOT NULL,
    PPRICE NUMBER(9) NOT NULL );
    
CREATE TABLE REVIEW(
    RNO NUMBER(6) PRIMARY KEY,
    PCODE VARCHAR2(30) REFERENCES PRODUCT(PCODE),
    MID VARCHAR2(30) REFERENCES MEMBER(MID),
    RGOOD NUMBER(6) DEFAULT 0,
    RHIT NUMBER(6) DEFAULT 0,
    RCONTENT VARCHAR2(4000),
    ODATE DATE NOT NULL);
    
CREATE TABLE REVIEW_FILE(
    RFNO VARCHAR2(30) PRIMARY KEY,
    RNO NUMBER(6) REFERENCES REVIEW(RNO),
    RFILE VARCHAR2(30) );
    
    
SELECT * FROM MEMBER;
SELECT * FROM GRADE;
SELECT * FROM AD;
