INSERT INTO GRADES (GNO, GNAME, LOWGRADE, HIGHGRADE)
VALUES (1,'NORMAL',0,1000000);
INSERT INTO GRADES (GNO, GNAME, LOWGRADE, HIGHGRADE)
VALUES (2,'GOLD',1000001,10000000);
INSERT INTO GRADES (GNO, GNAME, LOWGRADE, HIGHGRADE)
VALUES (3,'VIP',10000001,10000000);
INSERT INTO GRADES (GNO, GNAME, LOWGRADE, HIGHGRADE)
VALUES (4,'VVIP',10000001,999999999);

COMMIT;
SELECT * FROM GRADES;
SELECT M.*,AD_EMAIL,AD_PHONE,AD_CALL FROM MEMBER M,AD A WHERE M.MID = A.MID;

INSERT INTO MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS_BASIC,MADDRESS_DETAIL,MBIRTH
,MEMAIL,MGENDER,GNO) VALUES ('ID','111','이름','010','주소1','주소2','2017-08-21'
,'MAIL','남',1);
INSERT INTO AD (MID,AD_EMAIL,AD_PHONE,AD_CALL)
VALUES ('MIDDs',1,1,1);
SELECT M.*,a.ad_email,a.ad_phone,a.ad_call,G.GNAME FROM MEMBER M,AD A,GRADES G WHERE M.MID=A.MID AND M.GNO=G.GNO;

--상풍등록
UPDATE PRODUCT SET pdiscount = 30 WHERE PCODE='testPcode61';
COMMIT;

INSERT INTO PRODUCT (PCODE,MGID,PNAME,PPRICE,PIMAGE,PSTOCK) VALUES ('DA','MGID''SS',1000,'DD',100);
ROLLBACK;

--고객센터 게시판 글 작성
INSERT INTO customer_service (CNO,MID,CCONTENT,CSECRET,ONO) VALUES 
(CNO_SEQ.NEXTVAL,'test111','내용','1',null); --고객이 글 작성
commit;

UPDATE customer_service SET ccontent='',csecret=0,CHIT=0,CRDATE=SYSDATE,ONO='' WHERE CNO=1;
DELETE FROM customer_service WHERE CNO=1;
SELECT * FROM customer_service;

select * from ad;

select * from member;
UPDATE MEMBER SET MPW='',MNAME='',MPHONE='',MADDRESS='',MBIRTH=SYSDATE,MEMAIL='',MGENDER='';
SELECT * FROM ad;

UPDATE AD SET ad_email=0,ad_phone=1,ad_call=0 WHERE MID='aaa';
commit;

-- 배송업체등록
SELECT * FROM DELIVERY;

INSERT INTO DELIVERY (DNO,DNAME,DPHONE,DPRICE,DCOMPANY,DADDRESS) VALUES (DNO_SEQ.NEXTVAL,'배송','1234-11',2500,'한진','서울');
UPDATE DELIVERY SET PARRIVE_DATE = SYSDATE WHERE DNO=1;
COMMIT;
SELECT * FROM review WHERE PCODE='testPcode1';
-- 리뷰쓰기
INSERT INTO REVIEW (RNO,PCODE,MID,RIMAGE1,RIMAGE2,RIMAGE3,RSTAR,RCONTENT) VALUES (RNO_SEQ.NEXTVAL,?,?,?,?,?,?,?);
--리뷰 수정
UPDATE REVIEW SET PCODE=?,RIMAGE1=?,RIMAGE2=?,RIMAGE3=?,RSTAR=?,RCONTENT=? WHERE RNO=?;

--좋아요 한 아이디 확인
SELECT * FROM review_rgood WHERE rno='aaa';
INSERT INTO review_rgood VALUES (RGNO_SEQ.nextval,'MID',199);
COMMIT;

--리뷰 댓글 쓰기
INSERT INTO REVIEW_COMMENT (RCNO,RNO,MGID,RCCONTENT) VALUES (RCNO_SEQ.nextval,2,'admin','댓글내용');

SELECT * FROM REVIEW_COMMENT;
UPDATE REVIEW SET RCEXIST=1 WHERE RNO=1;
SELECT * FROM REVIEW;
SELECT * FROM REVIEW_COMMENT WHERE RNO=1;
UPDATE REVIEW SET RCEXIST=1 WHERE RNO=2; 

--장바구니에 추가한 제품인지 확인
SELECT * FROM CART WHERE MID='aaa' AND PCODE='testPcode3';
--주문 성공 후 카트 비우기
DELETE FROM CART WHERE MID='aaa';
INSERT INTO CART VALUES (CTNO_SEQ.NEXTVAL,?,?,?,?);
DELETE FROM CART WHERE MID='aaa';
