SELECT * FROM AD;
SELECT * FROM GRADE;
SELECT * FROM DELIVERY;
SELECT * FROM PRODUCT;
SELECT * FROM MEMBER;
SELECT * FROM CUSTOMER_SERVICE;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAIL;
SELECT * FROM REVIEW;
SELECT * FROM REVIEW_FILE;
SELECT * FROM MANAGER;

--로그인 시 MID,MPW로 DTO가져오기
SELECT M.*,a.ad_email,a.ad_phone,a.ad_call FROM MEMBER M,AD A WHERE M.MID=A.MID;
SELECT M.*,a.ad_email,a.ad_phone,a.ad_call FROM MEMBER M,AD A WHERE M.MID=A.MID AND M.MID='ID';
SELECT M.*,a.ad_email,a.ad_phone,a.ad_call FROM MEMBER M,AD A WHERE M.MID=A.MID AND M.MID='ID' AND M.MPW='111';

SELECT * FROM MANAGER WHERE MGID='' AND MGPW='';