SELECT * FROM AD;
SELECT * FROM GRADES;
SELECT * FROM DELIVERY;
SELECT * FROM PRODUCT;
SELECT * FROM MEMBER;

SELECT * FROM CUSTOMER_SERVICE;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAIL;
SELECT * FROM REVIEW;
SELECT * FROM MANAGER;

--로그인 시 MID,MPW로 DTO가져오기
SELECT M.*,a.ad_email,a.ad_phone,a.ad_call FROM MEMBER M,AD A WHERE M.MID=A.MID;
SELECT M.*,a.ad_email,a.ad_phone,a.ad_call FROM MEMBER M,AD A WHERE M.MID=A.MID AND M.MID='ID';
SELECT M.*,a.ad_email,a.ad_phone,a.ad_call FROM MEMBER M,AD A WHERE M.MID=A.MID AND M.MID='ID' AND M.MPW='111';

SELECT * FROM MANAGER WHERE MGID='' AND MGPW='';
SELECT * FROM MANAGER WHERE MGID='1';

SELECT COUNT(*) FROM PRODUCT;
-- product 정렬 top-n

SELECT * FROM PRODUCT ORDER BY preview_count DESC;

SELECT * FROM PRODUCT ORDER BY PREGIST DESC, preview_count DESC;

SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT P.*,M.MGNAME FROM PRODUCT P,MANAGER M WHERE P.MGID = M.MGID ORDER BY PPRICE, preview_count DESC) A)
 WHERE RN BETWEEN 5 AND 10;

SELECT * FROM (SELECT ROWNUM RN,C.* FROM (SELECT CS.*,M.MNAME FROM CUSTOMER_SERVICE CS, MEMBER M WHERE CS.MID=M.MID ORDER BY CGROUP DESC,CGROUP_OUTNUM) C)
    WHERE RN BETWEEN 5 AND 10;
    
SELECT CS.*,M.MNAME FROM customer_service CS, MEMBER M WHERE CNO='1';

SELECT M.*,ONO FROM MEMBER M, ORDERS O WHERE M.MID=O.MID AND M.MID='aaa';
SELECT * FROM ORDERS;

INSERT INTO ORDERS VALUES(ONO_SEQ.NEXTVAL,SYSDATE,NULL,'WWW','aaa');

SELECT * FROM DELIVERY;
INSERT INTO DELIVERY (DNO,DPRICE,DCOMPANY,parrive_date) VALUES('WWW',2500,'한진',NULL);

COMMIT;